import { Book, BorrowingRecord, Donation, AssistantAccount, LibraryNotification } from './types';

// Unsplash handpicked high-quality technology/learning cover images
export const IMAGES = {
  algorithms: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=400&h=500&q=80',
  systems: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=400&h=500&q=80',
  webDev: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=400&h=500&q=80',
  databases: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=400&h=500&q=80',
  architecture: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?auto=format&fit=crop&w=400&h=500&q=80',
  aiMl: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=400&h=500&q=80',
  devOps: 'https://images.unsplash.com/photo-1618401471353-b98aedd07871?auto=format&fit=crop&w=400&h=500&q=80',
  languages: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=400&h=500&q=80'
};

export const INITIAL_BOOKS: Book[] = [
  // --- ALGORITHMS (5) ---
  {
    id: 'alg-01',
    title: 'Introduction to Algorithms, 4th Ed.',
    author: 'Thomas H. Cormen, Charles E. Leiserson',
    isbn: '9780262046305',
    genre: 'Algorithms',
    description: 'The golden book in algorithm studies, offering an in-depth and mathematically precise introduction to computer algorithms and data structures.',
    imageUrl: IMAGES.algorithms,
    shelfLocation: 'ALG-A101',
    totalCopies: 4,
    availableCopies: 3,
  },
  {
    id: 'alg-02',
    title: 'Grokking Algorithms',
    author: 'Aditya Bhargava',
    isbn: '9781617292231',
    genre: 'Algorithms',
    description: 'An illustrated, friendly guide that teaches you how to apply common algorithms to practical software development problems.',
    imageUrl: IMAGES.algorithms,
    shelfLocation: 'ALG-B202',
    totalCopies: 3,
    availableCopies: 2,
  },
  {
    id: 'alg-03',
    title: 'The Algorithm Design Manual',
    author: 'Steven S. Skiena',
    isbn: '9781849967204',
    genre: 'Algorithms',
    description: 'A superb reference handbook for programmers, offering algorithm designs, implementation heuristics, and a full catalog of resources.',
    imageUrl: IMAGES.algorithms,
    shelfLocation: 'ALG-C303',
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    id: 'alg-04',
    title: 'Algorithms in C++',
    author: 'Robert Sedgewick',
    isbn: '9780201314526',
    genre: 'Algorithms',
    description: 'Deep exploration of data structures and algorithms in C++ covering fundamental, sorting, and graph structures.',
    imageUrl: IMAGES.algorithms,
    shelfLocation: 'ALG-D404',
    totalCopies: 2,
    availableCopies: 1,
  },
  {
    id: 'alg-05',
    title: 'Data Structures and Efficient Algorithms',
    author: 'Kurt Mehlhorn',
    isbn: '9783540136293',
    genre: 'Algorithms',
    description: 'Covers major efficient storage mechanisms, computational complexity bounds, and specialized data structures.',
    imageUrl: IMAGES.algorithms,
    shelfLocation: 'ALG-E505',
    totalCopies: 2,
    availableCopies: 2,
  },

  // --- SYSTEMS (5) ---
  {
    id: 'sys-01',
    title: "Computer Systems: A Programmer's Perspective",
    author: 'Randal E. Bryant, David R. O\'Hallaron',
    isbn: '9780134092669',
    genre: 'Systems',
    description: 'Explains the inner workings of computers from the perspective of how they execute hardware/software boundaries.',
    imageUrl: IMAGES.systems,
    shelfLocation: 'SYS-A101',
    totalCopies: 3,
    availableCopies: 2,
  },
  {
    id: 'sys-02',
    title: 'Operating Systems: Three Easy Pieces',
    author: 'Remzi H. Arpaci-Dusseau',
    isbn: '9781985336599',
    genre: 'Systems',
    description: 'An engaging textbook covering Virturalization, Concurrency, and Persistence in modern operating system architectures.',
    imageUrl: IMAGES.systems,
    shelfLocation: 'SYS-B202',
    totalCopies: 2,
    availableCopies: 1,
  },
  {
    id: 'sys-03',
    title: 'Linux Kernel Development',
    author: 'Robert Love',
    isbn: '9780672329463',
    genre: 'Systems',
    description: 'Provides deep, authoritative coverage of the design, scheduler mechanics, and execution internals of the Linux core.',
    imageUrl: IMAGES.systems,
    shelfLocation: 'SYS-C303',
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    id: 'sys-04',
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    isbn: '9781449373320',
    genre: 'Systems',
    description: 'An absolute masterpiece exploring the architectural principles of databases, distributed nodes, stream processing, and scalability.',
    imageUrl: IMAGES.systems,
    shelfLocation: 'SYS-D404',
    totalCopies: 5,
    availableCopies: 4,
  },
  {
    id: 'sys-05',
    title: 'Modern Operating Systems, 5th Ed.',
    author: 'Andrew S. Tanenbaum',
    isbn: '9780130313583',
    genre: 'Systems',
    description: 'Clear, classic conceptual foundation teaching process allocation, virtual memory, scheduling, and filesystems.',
    imageUrl: IMAGES.systems,
    shelfLocation: 'SYS-E505',
    totalCopies: 3,
    availableCopies: 3,
  },

  // --- WEB DEV (5) ---
  {
    id: 'web-01',
    title: 'Eloquent JavaScript, 3rd Ed.',
    author: 'Marijn Haverbeke',
    isbn: '9781593279509',
    genre: 'Web Dev',
    description: 'A deep dive into writing digital elegance with JS, covering functional patterns, browser integrations, and async scripting.',
    imageUrl: IMAGES.webDev,
    shelfLocation: 'WEB-A101',
    totalCopies: 5,
    availableCopies: 5,
  },
  {
    id: 'web-02',
    title: 'You Don\'t Know JS Yet: Scope & Closures',
    author: 'Kyle Simpson',
    isbn: '9781098110595',
    genre: 'Web Dev',
    description: 'Demystifies Javascript core execution scopes, compiler loops, closure scopes, and lexical environments.',
    imageUrl: IMAGES.webDev,
    shelfLocation: 'WEB-B202',
    totalCopies: 4,
    availableCopies: 4,
  },
  {
    id: 'web-03',
    title: 'Learning React: Modern Web Training',
    author: 'Eve Porcello, Alex Banks',
    isbn: '9781492051442',
    genre: 'Web Dev',
    description: 'A comprehensive, functional introduction to declarative React UI programming, React hooks, and application state models.',
    imageUrl: IMAGES.webDev,
    shelfLocation: 'WEB-C303',
    totalCopies: 3,
    availableCopies: 2,
  },
  {
    id: 'web-04',
    title: 'CSS Secrets',
    author: 'Lea Verou',
    isbn: '9781449372637',
    genre: 'Web Dev',
    description: 'Provides over forty clever, practical tips to solve daily layout, design, and styling challenges in responsive CSS.',
    imageUrl: IMAGES.webDev,
    shelfLocation: 'WEB-D404',
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    id: 'web-05',
    title: 'Full-Stack Web Development with Node',
    author: 'David Herron',
    isbn: '9781838848132',
    genre: 'Web Dev',
    description: 'Build robust, highly scalable backends, websockets, routing protocols, and RESTful APIs using the Node engine.',
    imageUrl: IMAGES.webDev,
    shelfLocation: 'WEB-E505',
    totalCopies: 2,
    availableCopies: 1,
  },

  // --- DATABASES (5) ---
  {
    id: 'db-01',
    title: 'Database System Concepts, 7th Ed.',
    author: 'Abraham Silberschatz, Henry F. Korth',
    isbn: '9780078022135',
    genre: 'Databases',
    description: 'The standard academic encyclopedia covering transactions, schemas, queries, recovery algorithms, and internal relational models.',
    imageUrl: IMAGES.databases,
    shelfLocation: 'DB-A101',
    totalCopies: 3,
    availableCopies: 3,
  },
  {
    id: 'db-02',
    title: 'SQL Antipatterns',
    author: 'Bill Karwin',
    isbn: '9781934356555',
    genre: 'Databases',
    description: 'Indispensable guide teaching how to avoid catastrophic design mistakes in SQL structures, schema generation, and indexing programs.',
    imageUrl: IMAGES.databases,
    shelfLocation: 'DB-B202',
    totalCopies: 2,
    availableCopies: 1,
  },
  {
    id: 'db-03',
    title: 'High Performance MySQL',
    author: 'Silvia Botros, Jeremy Tinley',
    isbn: '9781492080510',
    genre: 'Databases',
    description: 'Covers advanced index optimizations, query profiling, server replication, high availability, and massive database deployments.',
    imageUrl: IMAGES.databases,
    shelfLocation: 'DB-C303',
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    id: 'db-04',
    title: 'NoSQL Distilled',
    author: 'Pramod J. Sadalage, Martin Fowler',
    isbn: '9780321826626',
    genre: 'Databases',
    description: 'A brief guide to the emerging world of polyglot persistence, mapping key-value, document, column-family, and graph databases.',
    imageUrl: IMAGES.databases,
    shelfLocation: 'DB-D404',
    totalCopies: 4,
    availableCopies: 4,
  },
  {
    id: 'db-05',
    title: 'Designing Data Systems for Scalability',
    author: 'Girish Kumar',
    isbn: '9781789617269',
    genre: 'Databases',
    description: 'A practitioner guide teaching index clustering, active-passive replications, sharding keys, and eventual consistency bounds.',
    imageUrl: IMAGES.databases,
    shelfLocation: 'DB-E505',
    totalCopies: 1,
    availableCopies: 1,
  },

  // --- ARCHITECTURE (5) ---
  {
    id: 'arch-01',
    title: 'Clean Architecture',
    author: 'Robert C. Martin',
    isbn: '9780134494166',
    genre: 'Architecture',
    description: 'Presents the timeless rules of software structuring regarding bounds, dependencies, components, and modular boundaries.',
    imageUrl: IMAGES.architecture,
    shelfLocation: 'AR-A101',
    totalCopies: 5,
    availableCopies: 4,
  },
  {
    id: 'arch-02',
    title: 'Fundamentals of Software Architecture',
    author: 'Mark Richards, Neal Ford',
    isbn: '9781492043454',
    genre: 'Architecture',
    description: 'An modern look at software architecture patterns, focusing on modularity, microservices, component scopes, and soft skills.',
    imageUrl: IMAGES.architecture,
    shelfLocation: 'AR-B202',
    totalCopies: 3,
    availableCopies: 3,
  },
  {
    id: 'arch-03',
    title: 'Patterns of Enterprise Application Architecture',
    author: 'Martin Fowler',
    isbn: '9780321127426',
    genre: 'Architecture',
    description: 'Timeless architectural catalogs teaching domain models, active records, transaction scripts, and remote gateways.',
    imageUrl: IMAGES.architecture,
    shelfLocation: 'AR-C303',
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    id: 'arch-04',
    title: 'Domain-Driven Design: Tackling Complexity',
    author: 'Eric Evans',
    isbn: '9780321125217',
    genre: 'Architecture',
    description: 'The foundational standard for implementing DDD, mapping software code directly to core business logic models.',
    imageUrl: IMAGES.architecture,
    shelfLocation: 'AR-D404',
    totalCopies: 3,
    availableCopies: 2,
  },
  {
    id: 'arch-05',
    title: 'Software Architecture in Practice',
    author: 'Len Bass, Paul Clements',
    isbn: '9780136886099',
    genre: 'Architecture',
    description: 'Covers attributes such as performance, security, availability, and usability under strict quality assurance benchmarks.',
    imageUrl: IMAGES.architecture,
    shelfLocation: 'AR-E505',
    totalCopies: 2,
    availableCopies: 2,
  },

  // --- AI / ML (5) ---
  {
    id: 'ai-01',
    title: 'Hands-On Machine Learning with Scikit-Learn',
    author: 'Aurélien Géron',
    isbn: '9781492032649',
    genre: 'AI/ML',
    description: 'The gold standard practical guide for developing classification, regression, forest, and neural networks using python frameworks.',
    imageUrl: IMAGES.aiMl,
    shelfLocation: 'AI-A101',
    totalCopies: 4,
    availableCopies: 3,
  },
  {
    id: 'ai-02',
    title: 'Deep Learning',
    author: 'Ian Goodfellow, Yoshua Bengio',
    isbn: '9780262035613',
    genre: 'AI/ML',
    description: 'The mathematical bible of deep learning, detail-covering optimization math, feedforward layers, recurrent modules, and GANs.',
    imageUrl: IMAGES.aiMl,
    shelfLocation: 'AI-B202',
    totalCopies: 3,
    availableCopies: 3,
  },
  {
    id: 'ai-03',
    title: 'Artificial Intelligence: A Modern Approach',
    author: 'Stuart Russell, Peter Norvig',
    isbn: '9780134610993',
    genre: 'AI/ML',
    description: 'Comprehensive overview of AI covering rational search, probability models, neural logic, planning, and neural NLP.',
    imageUrl: IMAGES.aiMl,
    shelfLocation: 'AI-C303',
    totalCopies: 4,
    availableCopies: 4,
  },
  {
    id: 'ai-04',
    title: 'Generative Deep Learning, 2nd Ed.',
    author: 'David Foster',
    isbn: '9781098134181',
    genre: 'AI/ML',
    description: 'A marvelous modern workbook on creative AI, including diffusion models, GPT transformers, VAEs, and LLM orchestration.',
    imageUrl: IMAGES.aiMl,
    shelfLocation: 'AI-D404',
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    id: 'ai-05',
    title: 'Machine Learning Engineering in Systems',
    author: 'Andriy Burkov',
    isbn: '9781999579579',
    genre: 'AI/ML',
    description: 'A neat, practical industry roadmap detailing pipelining, training pipelines, data drifts, and inference speeds.',
    imageUrl: IMAGES.aiMl,
    shelfLocation: 'AI-E505',
    totalCopies: 2,
    availableCopies: 2,
  },

  // --- DEVOPS (5) ---
  {
    id: 'dev-01',
    title: 'The Phoenix Project',
    author: 'Gene Kim, Kevin Behr, George Spafford',
    isbn: '9780988262591',
    genre: 'DevOps',
    description: 'A highly engaging tech-novel that demonstrates how modern DevOps practices transform an endangered code rollout.',
    imageUrl: IMAGES.devOps,
    shelfLocation: 'DO-A101',
    totalCopies: 5,
    availableCopies: 5,
  },
  {
    id: 'dev-02',
    title: 'Site Reliability Engineering (SRE)',
    author: 'Niall Richard Murphy, Betsy Beyer',
    isbn: '9781491929124',
    genre: 'DevOps',
    description: 'Sheds actual light on massive Google operations regarding uptime, monitoring alerts, error budgets, and system health.',
    imageUrl: IMAGES.devOps,
    shelfLocation: 'DO-B202',
    totalCopies: 3,
    availableCopies: 3,
  },
  {
    id: 'dev-03',
    title: 'Accelerate: Building High Performing Teams',
    author: 'Nicole Forsgren, Jez Humble',
    isbn: '9781942788331',
    genre: 'DevOps',
    description: 'A scientifically backed study of modern software delivery performance, agility metrics, and technical leadership structures.',
    imageUrl: IMAGES.devOps,
    shelfLocation: 'DO-C303',
    totalCopies: 2,
    availableCopies: 1,
  },
  {
    id: 'dev-04',
    title: 'Continuous Delivery',
    author: 'Jez Humble, David Farley',
    isbn: '9780321601919',
    genre: 'DevOps',
    description: 'The definitive blueprint for setting up error-free build, test, and release deployments via automated pipelining systems.',
    imageUrl: IMAGES.devOps,
    shelfLocation: 'DO-D404',
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    id: 'dev-05',
    title: 'Docker Deep Dive',
    author: 'Nigel Poulton',
    isbn: '9781521203996',
    genre: 'DevOps',
    description: 'A comprehensive, very accessible handbook mapping container virtualization, images, layers, networks, and docker swarms.',
    imageUrl: IMAGES.devOps,
    shelfLocation: 'DO-E505',
    totalCopies: 3,
    availableCopies: 3,
  },

  // --- LANGUAGES (5) ---
  {
    id: 'lang-01',
    title: 'The C Programming Language, 2nd Ed.',
    author: 'Brian W. Kernighan, Dennis M. Ritchie',
    isbn: '9780131103627',
    genre: 'Languages',
    description: 'The historically essential reference book detailing the absolute foundational architecture of C compilers and pointers.',
    imageUrl: IMAGES.languages,
    shelfLocation: 'LN-A101',
    totalCopies: 3,
    availableCopies: 2,
  },
  {
    id: 'lang-02',
    title: 'Effective C++: 55 Specific Ways',
    author: 'Scott Meyers',
    isbn: '9780321334879',
    genre: 'Languages',
    description: 'Critical tips and style design elements to master memory leaks, copy constructors, templates, and pointers.',
    imageUrl: IMAGES.languages,
    shelfLocation: 'LN-B202',
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    id: 'lang-03',
    title: 'Programming Rust, 2nd Ed.',
    author: 'Jim Blandy, Jason Orendorff',
    isbn: '9781492052593',
    genre: 'Languages',
    description: 'Unlock how Rust achieves memory safety, blistering processing speeds, and safe concurrency without garbage collectors.',
    imageUrl: IMAGES.languages,
    shelfLocation: 'LN-C303',
    totalCopies: 3,
    availableCopies: 3,
  },
  {
    id: 'lang-04',
    title: 'Effective Java, 3rd Ed.',
    author: 'Joshua Bloch',
    isbn: '9780134685991',
    genre: 'Languages',
    description: 'Provides the standard coding guidelines defining optimal classes, generics, enums, lambdas, serializations, and methods.',
    imageUrl: IMAGES.languages,
    shelfLocation: 'LN-D404',
    totalCopies: 4,
    availableCopies: 3,
  },
  {
    id: 'lang-05',
    title: 'Fluent Python, 2nd Ed.',
    author: 'Luciano Ramalho',
    isbn: '9781492056324',
    genre: 'Languages',
    description: 'A programmer\'s technical manual explaining how to write elegant, idiomatic, and highly optimized Python code.',
    imageUrl: IMAGES.languages,
    shelfLocation: 'LN-E505',
    totalCopies: 3,
    availableCopies: 2,
  }
];

// Seed transactional records
// Note: Today is 2026-05-25.
// Let's make an overdue record (borrowed on 2026-05-01, due 2026-05-15, overdue by 10 days => fine is $10).
export const INITIAL_RECORDS: BorrowingRecord[] = [
  {
    id: 'rec-01',
    studentId: 'U2023101',
    studentName: 'Alex Mercer',
    bookId: 'alg-04', // Algorithms in C++
    bookTitle: 'Algorithms in C++',
    borrowDate: '2026-05-02',
    dueDate: '2026-05-16',
    status: 'Borrowed', // Overdue calculation is dynamic based on system date vs due date!
    fineAmount: 9, // fine is active because returned is undefined and current date is May 25th 2026!
    finePaid: false
  },
  {
    id: 'rec-02',
    studentId: 'U2023101',
    studentName: 'Alex Mercer',
    bookId: 'sys-02', // Operating Systems: Three Easy Pieces
    bookTitle: 'Operating Systems: Three Easy Pieces',
    borrowDate: '2026-05-12',
    dueDate: '2026-05-26', // still active, not overdue (due tomorrow)
    status: 'Borrowed',
    fineAmount: 0,
    finePaid: false
  },
  {
    id: 'rec-03',
    studentId: 'U2023102',
    studentName: 'Sarah Connor',
    bookId: 'web-05', // Full-Stack Web Dev
    bookTitle: 'Full-Stack Web Development with Node',
    borrowDate: '2026-05-20',
    dueDate: '2026-06-03',
    status: 'Borrowed',
    fineAmount: 0,
    finePaid: false
  },
  {
    id: 'rec-04',
    studentId: 'U2023103',
    studentName: 'Bruce Banner',
    bookId: 'db-02', // SQL Antipatterns
    bookTitle: 'SQL Antipatterns',
    borrowDate: '2026-05-05',
    dueDate: '2026-05-19', // overdue by 6 days -> fine $6
    status: 'Borrowed',
    fineAmount: 6,
    finePaid: false
  },
  {
    id: 'rec-05',
    studentId: 'U2023101',
    studentName: 'Alex Mercer',
    bookId: 'arch-01', // Clean Architecture
    bookTitle: 'Clean Architecture',
    borrowDate: '2026-04-10',
    dueDate: '2026-04-24',
    returnDate: '2026-04-22', // Returned in time
    status: 'Returned',
    fineAmount: 0,
    finePaid: false
  },
  {
    id: 'rec-06',
    studentId: 'U2023104',
    studentName: 'Clark Kent',
    bookId: 'lang-01', // The C Programming Language
    bookTitle: 'The C Programming Language, 2nd Ed.',
    borrowDate: '2026-04-01',
    dueDate: '2026-04-15',
    returnDate: '2026-04-20', // Returned 5 days late
    status: 'Returned',
    fineAmount: 5,
    finePaid: true // Paid
  }
];

// Seed donations
export const INITIAL_DONATIONS: Donation[] = [
  {
    id: 'don-01',
    donorId: 'U2023101',
    donorName: 'Alex Mercer',
    bookTitle: 'JavaScript: The Good Parts',
    author: 'Douglas Crockford',
    isbn: '9780596517748',
    genre: 'Web Dev',
    donationType: 'Permanent',
    status: 'Pending',
    requestedAt: '2026-05-24'
  },
  {
    id: 'don-02',
    donorId: 'U2023102',
    donorName: 'Sarah Connor',
    bookTitle: 'Programming Pearls',
    author: 'Jon Bentley',
    isbn: '9780201657883',
    genre: 'Algorithms',
    donationType: 'Temporary',
    durationMonths: 6,
    status: 'Approved',
    requestedAt: '2026-05-18'
  },
  {
    id: 'don-03',
    donorId: 'U2023103',
    donorName: 'Bruce Banner',
    bookTitle: 'Cracking the Coding Interview',
    author: 'Gayle Laakmann McDowell',
    isbn: '9780984782857',
    genre: 'Algorithms',
    donationType: 'Permanent',
    status: 'Rejected',
    rejectionReason: 'The library already holds multiple copy bundles of this specific edition.',
    requestedAt: '2026-05-15'
  }
];

// Seed initial assistant accounts
export const INITIAL_ASSISTANTS: AssistantAccount[] = [
  {
    id: 'AST001',
    name: 'Emily Watson',
    email: 'emily.w@university.edu',
    createdAt: '2026-01-15'
  },
  {
    id: 'AST002',
    name: 'Marcus Vance',
    email: 'marcus.v@university.edu',
    createdAt: '2026-03-02'
  }
];

// Seed notifications
export const INITIAL_NOTIFICATIONS: LibraryNotification[] = [
  {
    id: 'notif-01',
    userId: 'U2023101',
    title: 'Upcoming Book Return Due ⏰',
    text: '"Operating Systems: Three Easy Pieces" is due tomorrow. Please return it or contact assistant at counter.',
    type: 'Alert',
    date: '2026-05-25',
    isRead: false
  },
  {
    id: 'notif-02',
    userId: 'U2023101',
    title: 'Donation Under Review 📚',
    text: 'Your donation request for "JavaScript: The Good Parts" has been submitted successfully and is awaiting manager approval.',
    type: 'Info',
    date: '2026-05-24',
    isRead: false
  },
  {
    id: 'notif-03',
    userId: 'U2023101',
    title: 'Donation Approved 🎉',
    text: 'Your temporary donation of "Programming Pearls" was approved. Shelf location is ALG-C303.',
    type: 'Success',
    date: '2026-05-18',
    isRead: true
  },
  {
    id: 'notif-04',
    userId: 'U2023103',
    title: 'Overdue Notice & Fine ⚠️',
    text: 'You have been charged $6 for overdue return of "SQL Antipatterns". Please settle payment to unblock borrowing.',
    type: 'Alert',
    date: '2026-05-19',
    isRead: false
  }
];
